export const urlConfigs = (item) => [
  {
    key: "1",
    url: "http://www.celestrak.com/NORAD/elements/weather.txt",
    name: item.weather,
    dataIndex: "weather",
    color: "BLUEVIOLET",
  },
  {
    key: "2",
    url: "http://www.celestrak.com/NORAD/elements/active.txt",
    name: item.active,
    dataIndex: "active",
    color: "DEEPSKYBLUE",
  },
  {
    key: "3",
    url: "http://www.celestrak.com/NORAD/elements/science.txt",
    name: item.science,
    dataIndex: "science",
    color: "GOLD",
  },
  {
    key: "4",
    url: "http://www.celestrak.com/NORAD/elements/stations.txt",
    name: item.stations,
    dataIndex: "stations",
    color: "HOTPINK",
  },
  {
    key: "5",
    url: "http://www.celestrak.com/NORAD/elements/cosmos-2251-debris.txt",
    name: item.debris,
    dataIndex: "debris",
    color: "RED",
  },
  {
    key: "6",
    url: "http://www.celestrak.com/NORAD/elements/iridium-NEXT.txt",
    name: item.iridium,
    dataIndex: "iridium",
    color: "LAWNGREEN",
  },
  {
    key: "7",
    url: "http://www.celestrak.com/NORAD/elements/gps-ops.txt",
    name: item.gps,
    dataIndex: "gps",
    color: "MEDIUMBLUE",
  },
  {
    key: "8",
    url: "http://www.celestrak.com/NORAD/elements/ses.txt",
    name: item.ses,
    dataIndex: "ses",
    color: "ORANGERED",
  },
  {
    key: "9",
    url: "http://www.celestrak.com/NORAD/elements/starlink.txt",
    name: item.starlink,
    dataIndex: "starlink",
    color: "WHITE",
  },
];
